# Generated by Django 2.0.2 on 2018-02-05 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='shirts_size',
            new_name='shirt_size',
        ),
    ]
