# Generated by Django 2.0.2 on 2018-02-06 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0007_auto_20180206_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('from_user', 'to_user')},
        ),
    ]
