# Generated by Django 2.0.2 on 2018-02-09 06:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyPerson1',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('proxy_manager.person',),
            managers=[
                ('secondary', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MyPerson2',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('proxy_manager.person', models.Model),
        ),
    ]
